import { db, blogPostsTable, destinationsTable, galleryPhotosTable } from "@workspace/db";
import { count } from "drizzle-orm";

const destinations = [
  { name: "Sylhet", slug: "sylhet", region: "Sylhet Division", description: "Sylhet is a sensory feast — the smell of tea leaves at dawn, the sound of the Surma River, the sight of endless emerald hillsides. It's one of those places that feels like the world slowing down just for you.", coverImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", bestTimeToVisit: "October – March", published: true },
  { name: "Rangamati", slug: "rangamati", region: "Chittagong Hill Tracts", description: "Nestled in the Chittagong Hill Tracts, Rangamati is a world apart — a tapestry of turquoise water, wooden stilt houses, and the vibrant traditions of the Chakma and Marma peoples.", coverImageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80", bestTimeToVisit: "November – February", published: true },
  { name: "Cox's Bazar", slug: "coxs-bazar", region: "Chittagong Division", description: "Cox's Bazar is where Bangladesh lets its hair down. The beach is endless, the sunsets are amber fire, and the dried fish markets have a character all their own.", coverImageUrl: "https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=800&q=80", bestTimeToVisit: "November – March", published: true },
  { name: "Chittagong", slug: "chittagong", region: "Chittagong Division", description: "Chittagong is Bangladesh's city of contradictions — colonial bungalows beside bustling port cranes, Buddhist pagodas beside tea stalls.", coverImageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80", bestTimeToVisit: "October – February", published: true },
  { name: "Rajshahi", slug: "rajshahi", region: "Rajshahi Division", description: "Rajshahi is the quiet achiever — a city of wide boulevards and scholars, where ancient terracotta temples crumble beautifully in mango groves.", coverImageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", bestTimeToVisit: "November – February", published: true },
  { name: "Dhaka", slug: "dhaka", region: "Dhaka Division", description: "Dhaka is a city that demands your full attention. The old city unfolds in layers — Mughal mosques, rickshaw art, the smell of biryani and jamdani silk.", coverImageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80", bestTimeToVisit: "October – February", published: true },
  { name: "Manikganj", slug: "manikganj", region: "Dhaka Division", description: "Manikganj is where you go to slow down. The rivers are everything here — children bathing, fishermen casting nets, ferries plying the monsoon flood.", coverImageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80", bestTimeToVisit: "July – October", published: true },
  { name: "Dinajpur", slug: "dinajpur", region: "Rangpur Division", description: "Dinajpur's Kantajew Temple is one of the finest terracotta monuments in Bangladesh — every brick tells a story from the Ramayana and Mahabharata.", coverImageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", bestTimeToVisit: "October – March", published: true },
  { name: "Tangail", slug: "tangail", region: "Dhaka Division", description: "Tangail is a study in slow time — the click of handlooms in dimly lit workshops, the crumbling columns of a nawab's palace, the mist over the Jamuna.", coverImageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80", bestTimeToVisit: "October – February", published: true },
  { name: "Noakhali", slug: "noakhali", region: "Chittagong Division", description: "Noakhali is the edge of the land — where Bangladesh literally ends and the Bay of Bengal begins. The char islands form and dissolve with the tides.", coverImageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80", bestTimeToVisit: "November – February", published: true },
];

const posts = [
  { title: "One Morning in Sylhet: Tea, Mist, and a Perfect Silence", slug: "one-morning-in-sylhet", excerpt: "We left the guesthouse before dawn. My daughter had insisted — something about golden hour and the tea gardens. She was right, of course. She usually is.", content: "We left the guesthouse before dawn. My daughter had insisted — something about golden hour and the tea gardens. She was right, of course. She usually is. The Srimangal hills were wrapped in mist when we arrived, and the first light turned the tea bushes to hammered copper. We ate steamed rice and dal by the roadside, served by a woman who spoke no English and needed none. Later, at Ratargul, we paddled through the swamp forest in a wooden boat, the canopy closing above us like a green cathedral. This is what we travel for.", coverImageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", published: true },
  { title: "Feeding the Family in Old Dhaka: A Culinary Pilgrimage", slug: "feeding-the-family-in-old-dhaka", excerpt: "There is a lane in Nazira Bazaar that smells of cardamom and old wood. We went there three mornings in a row. On the fourth, we brought notebooks.", content: "There is a lane in Nazira Bazaar that smells of cardamom and old wood. We went there three mornings in a row. On the fourth, we brought notebooks. The kacchi biryani at Al-Razzaque is not just food — it is history on a plate, unchanged for seventy years. My son, who claims to hate biryani in Dhaka, ate two helpings. The shahi jilapi from the 200-year-old shop near Ahsan Manzil dissolved on the tongue like spun sugar and memory. Old Dhaka doesn't just feed you. It rewrites you.", coverImageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80", published: true },
  { title: "Kaptai Lake at Dusk: What Water Remembers", slug: "kaptai-lake-at-dusk", excerpt: "The lake swallowed an entire valley — towns, paddy fields, a way of life — when the dam went up in 1962. It is beautiful and it is melancholy in equal measure.", content: "The lake swallowed an entire valley — towns, paddy fields, a way of life — when the dam went up in 1962. Standing at the Shuvolong waterfall and watching the water fall into Kaptai Lake, you feel the weight of what lies beneath. Our guide, a young Chakma man named Bipon, told us his grandmother remembered crossing the lake to reach her old village, which is now fifty feet underwater. At dusk, we watched the fishing boats come in, their lanterns reflected in water that holds so many secrets. Travel makes witnesses of us all.", coverImageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80", published: true },
  { title: "Crossing the Padma: Bangladesh by Slow Boat", slug: "crossing-the-padma", excerpt: "The Sadarghat rocket steamer is the most cinematic way to travel in Bangladesh. Arriving at dawn, the river wrapped in pearl fog, felt like entering a dream.", content: "The Sadarghat rocket steamer is the most cinematic way to travel in Bangladesh. We booked a first-class cabin — which is to say, a small room with a porthole and a fan — and watched the country unspool along the riverbanks. Villages appeared and disappeared. Women beat laundry on stone ghats. Cormorants dove beside the prow. Arriving at Barisal at dawn, the river wrapped in pearl fog, felt like entering a dream. This is the Bangladesh that no road can show you. You must take the water.", coverImageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80", published: true },
  { title: "Packing Light for Bangladesh: What Actually Works", slug: "packing-light-for-bangladesh", excerpt: "After eight trips to Bangladesh with two children, we've finally got our packing system down. Here's what we always bring — and what we always regret bringing.", content: "After eight trips to Bangladesh with two children, we've finally got our packing system down. The single most important item: a lightweight sarong. It is a towel, a sun shield, a picnic blanket, and a modesty wrap at mosque entrances. Second most important: oral rehydration salts. The heat is serious. Third: a curated first-aid kit that includes antihistamines, because mosquitoes find our family irresistible. What we stopped bringing: thick guide books, formal clothes, and worry.", coverImageUrl: "https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=800&q=80", published: true },
  { title: "Kantajew Temple: Where Every Brick Tells a Story", slug: "kantajew-temple", excerpt: "Dinajpur's Kantajew Temple is perhaps the finest example of terracotta temple art in all of Bengal. We spent four hours there and wished we had more.", content: "Dinajpur's Kantajew Temple is perhaps the finest example of terracotta temple art in all of Bengal. Built in 1752 by Maharaja Pran Nath, every square inch of its surface is covered in intricate terracotta tiles depicting scenes from the Ramayana and Mahabharata — dancing girls, battle scenes, river goddesses. My daughter spent an hour just documenting one wall panel. The temple lost its nine towering spires in the earthquake of 1897, making what remains an even more poignant treasure. Go in the morning light. The terracotta glows.", coverImageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", published: true },
  { title: "Monsoon in Bangladesh: Why We Chose the Wettest Season", slug: "monsoon-in-bangladesh", excerpt: "Everyone told us not to come in August. The roads flood. The sky is a constant gray smear. They were right about all of it. We'd come again in a heartbeat.", content: "Everyone told us not to come in August. The roads flood. The sky is a constant gray smear. The mosquitoes are catastrophic. They were right about all of it. We'd come again in a heartbeat. Monsoon Bangladesh is another country — green beyond any shade of green you know, rivers swollen to small oceans, villages accessible only by boat. In Manikganj, children swam in streets that were roads the week before. In Sylhet, the Ratargul swamp became a boat highway through a flooded forest. Rain is not the enemy of travel. It is the story.", coverImageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80", published: true },
  { title: "The Rickshaw Painters of Dhaka", slug: "rickshaw-painters-of-dhaka", excerpt: "Behind a workshop in Kamrangirchar, masters of an ancient folk art are painting the world onto the backs of cycle-rickshaws — and slowly disappearing.", content: "Behind a workshop in Kamrangirchar, masters of an ancient folk art are painting the world onto the backs of cycle-rickshaws — and slowly disappearing. Dhaka's rickshaw art is a UNESCO-acknowledged tradition that combines folk painting, storytelling, and commercial craft. Master painter Razzak, age 67, has been painting rickshaws for fifty years. His subjects are always the same and always different: Bollywood heroines, Bengal tigers, the Taj Mahal, Sundarbans mangroves. We watched him for two hours. He charged a finished panel one thousand taka. We paid five. He wouldn't have it any other way.", coverImageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80", published: true },
];

const photos = [
  { imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", caption: "Dawn over the Srimangal tea gardens, Sylhet" },
  { imageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80", caption: "Low tide at Inani Beach, Cox's Bazar" },
  { imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80", caption: "Morning mist on Kaptai Lake, Rangamati" },
  { imageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80", caption: "Sadarghat riverport at blue hour, Dhaka" },
  { imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80", caption: "Inside the Ratargul swamp forest, Sylhet" },
  { imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80", caption: "The port city skyline from Patenga beach" },
  { imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", caption: "Terracotta panels of Kantajew temple detail" },
  { imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", caption: "Sunset at the world's longest sea beach" },
  { imageUrl: "https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=800&q=80", caption: "Tribal village on the hillside, Rangamati" },
  { imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80", caption: "Lalbagh Fort through the jacaranda trees" },
  { imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", caption: "Tea pickers at first light, Srimangal" },
  { imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80", caption: "Fishing boats on the Padma at flood season" },
  { imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", caption: "Golden paddy fields in November, Dinajpur" },
  { imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80", caption: "Foy's Lake reflections, Chittagong" },
  { imageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80", caption: "A boat family on the Bay of Bengal" },
  { imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80", caption: "A weaver at his loom in Tangail" },
  { imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80", caption: "The hanging bridge at twilight, Rangamati" },
  { imageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80", caption: "Rickshaw art in the lanes of Old Dhaka" },
  { imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&q=80", caption: "Jaflong Zero Point on a clear morning" },
  { imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", caption: "Deer at dusk on Nijhum Dwip island" },
];

export async function seedIfEmpty() {
  const [{ value: destCount }] = await db.select({ value: count() }).from(destinationsTable);
  if (destCount > 0) return;

  await db.insert(destinationsTable).values(destinations);
  await db.insert(blogPostsTable).values(posts);
  await db.insert(galleryPhotosTable).values(photos);
}
